# CI was triggered at pull request
language: php

php:
  - 7.0
  - nightly

script:
  - sudo mkdir -p /home/log/esupdater/
  - sudo chmod -R 777 /home/log/
  - composer install
  - php test/run.php

branches:
  only:
    - v1.x
    - v2.x
